// <auto-generated />
namespace Cars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class car_database_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(car_database_init));
        
        string IMigrationMetadata.Id
        {
            get { return "202003200722161_car_database_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
